(cl:defpackage limb_core_msgs-msg
  (:use )
  (:export
   "<CONTACTSTATE>"
   "CONTACTSTATE"
   "<ENDPOINTSTATE>"
   "ENDPOINTSTATE"
   "<ENDPOINTSTATES>"
   "ENDPOINTSTATES"
   "<FLOAT64MULTIARRAY>"
   "FLOAT64MULTIARRAY"
   "<JOINTCOMMAND>"
   "JOINTCOMMAND"
   "<JOINTSTATE>"
   "JOINTSTATE"
   "<MARKERARRAY>"
   "MARKERARRAY"
   "<MARKERSTRINGARRAY>"
   "MARKERSTRINGARRAY"
   "<OBJECTINFO>"
   "OBJECTINFO"
   "<OBJECTTRAJECTORY>"
   "OBJECTTRAJECTORY"
   "<SHUTDOWNREASON>"
   "SHUTDOWNREASON"
   "<TACTILESTATE>"
   "TACTILESTATE"
  ))

