// Generated by gencpp from file limb_core_msgs/GetObjectTrajectory.msg
// DO NOT EDIT!


#ifndef LIMB_CORE_MSGS_MESSAGE_GETOBJECTTRAJECTORY_H
#define LIMB_CORE_MSGS_MESSAGE_GETOBJECTTRAJECTORY_H

#include <ros/service_traits.h>


#include <limb_core_msgs/GetObjectTrajectoryRequest.h>
#include <limb_core_msgs/GetObjectTrajectoryResponse.h>


namespace limb_core_msgs
{

struct GetObjectTrajectory
{

typedef GetObjectTrajectoryRequest Request;
typedef GetObjectTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetObjectTrajectory
} // namespace limb_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::limb_core_msgs::GetObjectTrajectory > {
  static const char* value()
  {
    return "670fd0fb651b5b6b3441cfb7fb2b33a4";
  }

  static const char* value(const ::limb_core_msgs::GetObjectTrajectory&) { return value(); }
};

template<>
struct DataType< ::limb_core_msgs::GetObjectTrajectory > {
  static const char* value()
  {
    return "limb_core_msgs/GetObjectTrajectory";
  }

  static const char* value(const ::limb_core_msgs::GetObjectTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::limb_core_msgs::GetObjectTrajectoryRequest> should match
// service_traits::MD5Sum< ::limb_core_msgs::GetObjectTrajectory >
template<>
struct MD5Sum< ::limb_core_msgs::GetObjectTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::limb_core_msgs::GetObjectTrajectory >::value();
  }
  static const char* value(const ::limb_core_msgs::GetObjectTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::limb_core_msgs::GetObjectTrajectoryRequest> should match
// service_traits::DataType< ::limb_core_msgs::GetObjectTrajectory >
template<>
struct DataType< ::limb_core_msgs::GetObjectTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::limb_core_msgs::GetObjectTrajectory >::value();
  }
  static const char* value(const ::limb_core_msgs::GetObjectTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::limb_core_msgs::GetObjectTrajectoryResponse> should match
// service_traits::MD5Sum< ::limb_core_msgs::GetObjectTrajectory >
template<>
struct MD5Sum< ::limb_core_msgs::GetObjectTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::limb_core_msgs::GetObjectTrajectory >::value();
  }
  static const char* value(const ::limb_core_msgs::GetObjectTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::limb_core_msgs::GetObjectTrajectoryResponse> should match
// service_traits::DataType< ::limb_core_msgs::GetObjectTrajectory >
template<>
struct DataType< ::limb_core_msgs::GetObjectTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::limb_core_msgs::GetObjectTrajectory >::value();
  }
  static const char* value(const ::limb_core_msgs::GetObjectTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIMB_CORE_MSGS_MESSAGE_GETOBJECTTRAJECTORY_H
