// Generated by gencpp from file limb_core_msgs/GetObjectTrajectoryResponse.msg
// DO NOT EDIT!


#ifndef LIMB_CORE_MSGS_MESSAGE_GETOBJECTTRAJECTORYRESPONSE_H
#define LIMB_CORE_MSGS_MESSAGE_GETOBJECTTRAJECTORYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace limb_core_msgs
{
template <class ContainerAllocator>
struct GetObjectTrajectoryResponse_
{
  typedef GetObjectTrajectoryResponse_<ContainerAllocator> Type;

  GetObjectTrajectoryResponse_()
    : success(false)  {
    }
  GetObjectTrajectoryResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetObjectTrajectoryResponse_

typedef ::limb_core_msgs::GetObjectTrajectoryResponse_<std::allocator<void> > GetObjectTrajectoryResponse;

typedef boost::shared_ptr< ::limb_core_msgs::GetObjectTrajectoryResponse > GetObjectTrajectoryResponsePtr;
typedef boost::shared_ptr< ::limb_core_msgs::GetObjectTrajectoryResponse const> GetObjectTrajectoryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator1> & lhs, const ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator1> & lhs, const ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace limb_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "limb_core_msgs/GetObjectTrajectoryResponse";
  }

  static const char* value(const ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetObjectTrajectoryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::limb_core_msgs::GetObjectTrajectoryResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIMB_CORE_MSGS_MESSAGE_GETOBJECTTRAJECTORYRESPONSE_H
