// Generated by gencpp from file limb_core_msgs/GetObjectTrajectoryRequest.msg
// DO NOT EDIT!


#ifndef LIMB_CORE_MSGS_MESSAGE_GETOBJECTTRAJECTORYREQUEST_H
#define LIMB_CORE_MSGS_MESSAGE_GETOBJECTTRAJECTORYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace limb_core_msgs
{
template <class ContainerAllocator>
struct GetObjectTrajectoryRequest_
{
  typedef GetObjectTrajectoryRequest_<ContainerAllocator> Type;

  GetObjectTrajectoryRequest_()
    : id()
    , pose()  {
    }
  GetObjectTrajectoryRequest_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetObjectTrajectoryRequest_

typedef ::limb_core_msgs::GetObjectTrajectoryRequest_<std::allocator<void> > GetObjectTrajectoryRequest;

typedef boost::shared_ptr< ::limb_core_msgs::GetObjectTrajectoryRequest > GetObjectTrajectoryRequestPtr;
typedef boost::shared_ptr< ::limb_core_msgs::GetObjectTrajectoryRequest const> GetObjectTrajectoryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator1> & lhs, const ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator1> & lhs, const ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace limb_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca24679b18012554617c5552db286b5e";
  }

  static const char* value(const ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca24679b18012554ULL;
  static const uint64_t static_value2 = 0x617c5552db286b5eULL;
};

template<class ContainerAllocator>
struct DataType< ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "limb_core_msgs/GetObjectTrajectoryRequest";
  }

  static const char* value(const ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id\n"
"geometry_msgs/PoseStamped[] pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetObjectTrajectoryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::limb_core_msgs::GetObjectTrajectoryRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "pose[]" << std::endl;
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      s << indent << "  pose[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIMB_CORE_MSGS_MESSAGE_GETOBJECTTRAJECTORYREQUEST_H
