// Generated by gencpp from file limb_core_msgs/GetObjectPose.msg
// DO NOT EDIT!


#ifndef LIMB_CORE_MSGS_MESSAGE_GETOBJECTPOSE_H
#define LIMB_CORE_MSGS_MESSAGE_GETOBJECTPOSE_H

#include <ros/service_traits.h>


#include <limb_core_msgs/GetObjectPoseRequest.h>
#include <limb_core_msgs/GetObjectPoseResponse.h>


namespace limb_core_msgs
{

struct GetObjectPose
{

typedef GetObjectPoseRequest Request;
typedef GetObjectPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetObjectPose
} // namespace limb_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::limb_core_msgs::GetObjectPose > {
  static const char* value()
  {
    return "b2cf2bdbfc28ab78c6337ab9541cda4c";
  }

  static const char* value(const ::limb_core_msgs::GetObjectPose&) { return value(); }
};

template<>
struct DataType< ::limb_core_msgs::GetObjectPose > {
  static const char* value()
  {
    return "limb_core_msgs/GetObjectPose";
  }

  static const char* value(const ::limb_core_msgs::GetObjectPose&) { return value(); }
};


// service_traits::MD5Sum< ::limb_core_msgs::GetObjectPoseRequest> should match
// service_traits::MD5Sum< ::limb_core_msgs::GetObjectPose >
template<>
struct MD5Sum< ::limb_core_msgs::GetObjectPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::limb_core_msgs::GetObjectPose >::value();
  }
  static const char* value(const ::limb_core_msgs::GetObjectPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::limb_core_msgs::GetObjectPoseRequest> should match
// service_traits::DataType< ::limb_core_msgs::GetObjectPose >
template<>
struct DataType< ::limb_core_msgs::GetObjectPoseRequest>
{
  static const char* value()
  {
    return DataType< ::limb_core_msgs::GetObjectPose >::value();
  }
  static const char* value(const ::limb_core_msgs::GetObjectPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::limb_core_msgs::GetObjectPoseResponse> should match
// service_traits::MD5Sum< ::limb_core_msgs::GetObjectPose >
template<>
struct MD5Sum< ::limb_core_msgs::GetObjectPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::limb_core_msgs::GetObjectPose >::value();
  }
  static const char* value(const ::limb_core_msgs::GetObjectPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::limb_core_msgs::GetObjectPoseResponse> should match
// service_traits::DataType< ::limb_core_msgs::GetObjectPose >
template<>
struct DataType< ::limb_core_msgs::GetObjectPoseResponse>
{
  static const char* value()
  {
    return DataType< ::limb_core_msgs::GetObjectPose >::value();
  }
  static const char* value(const ::limb_core_msgs::GetObjectPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIMB_CORE_MSGS_MESSAGE_GETOBJECTPOSE_H
