// Generated by gencpp from file limb_core_msgs/GetTactileStateResponse.msg
// DO NOT EDIT!


#ifndef LIMB_CORE_MSGS_MESSAGE_GETTACTILESTATERESPONSE_H
#define LIMB_CORE_MSGS_MESSAGE_GETTACTILESTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace limb_core_msgs
{
template <class ContainerAllocator>
struct GetTactileStateResponse_
{
  typedef GetTactileStateResponse_<ContainerAllocator> Type;

  GetTactileStateResponse_()
    : result(false)
    , header()
    , data()  {
    }
  GetTactileStateResponse_(const ContainerAllocator& _alloc)
    : result(false)
    , header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTactileStateResponse_

typedef ::limb_core_msgs::GetTactileStateResponse_<std::allocator<void> > GetTactileStateResponse;

typedef boost::shared_ptr< ::limb_core_msgs::GetTactileStateResponse > GetTactileStateResponsePtr;
typedef boost::shared_ptr< ::limb_core_msgs::GetTactileStateResponse const> GetTactileStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator1> & lhs, const ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator1> & lhs, const ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace limb_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d8412c5a901c57aefb9582d8e21ce43";
  }

  static const char* value(const ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d8412c5a901c57aULL;
  static const uint64_t static_value2 = 0xefb9582d8e21ce43ULL;
};

template<class ContainerAllocator>
struct DataType< ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "limb_core_msgs/GetTactileStateResponse";
  }

  static const char* value(const ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
"std_msgs/Header header\n"
"int16[] data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTactileStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::limb_core_msgs::GetTactileStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIMB_CORE_MSGS_MESSAGE_GETTACTILESTATERESPONSE_H
