// Generated by gencpp from file limb_core_msgs/GetTactileStateRequest.msg
// DO NOT EDIT!


#ifndef LIMB_CORE_MSGS_MESSAGE_GETTACTILESTATEREQUEST_H
#define LIMB_CORE_MSGS_MESSAGE_GETTACTILESTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace limb_core_msgs
{
template <class ContainerAllocator>
struct GetTactileStateRequest_
{
  typedef GetTactileStateRequest_<ContainerAllocator> Type;

  GetTactileStateRequest_()
    : id(0)  {
    }
  GetTactileStateRequest_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetTactileStateRequest_

typedef ::limb_core_msgs::GetTactileStateRequest_<std::allocator<void> > GetTactileStateRequest;

typedef boost::shared_ptr< ::limb_core_msgs::GetTactileStateRequest > GetTactileStateRequestPtr;
typedef boost::shared_ptr< ::limb_core_msgs::GetTactileStateRequest const> GetTactileStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator1> & lhs, const ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator1> & lhs, const ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace limb_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83303829ff5167a112112db2bf7b7905";
  }

  static const char* value(const ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83303829ff5167a1ULL;
  static const uint64_t static_value2 = 0x12112db2bf7b7905ULL;
};

template<class ContainerAllocator>
struct DataType< ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "limb_core_msgs/GetTactileStateRequest";
  }

  static const char* value(const ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n"
"\n"
;
  }

  static const char* value(const ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTactileStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::limb_core_msgs::GetTactileStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIMB_CORE_MSGS_MESSAGE_GETTACTILESTATEREQUEST_H
