// Generated by gencpp from file limb_core_msgs/GetTactileState.msg
// DO NOT EDIT!


#ifndef LIMB_CORE_MSGS_MESSAGE_GETTACTILESTATE_H
#define LIMB_CORE_MSGS_MESSAGE_GETTACTILESTATE_H

#include <ros/service_traits.h>


#include <limb_core_msgs/GetTactileStateRequest.h>
#include <limb_core_msgs/GetTactileStateResponse.h>


namespace limb_core_msgs
{

struct GetTactileState
{

typedef GetTactileStateRequest Request;
typedef GetTactileStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTactileState
} // namespace limb_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::limb_core_msgs::GetTactileState > {
  static const char* value()
  {
    return "2c24e2bd6b65d67db954ab24fe1a2513";
  }

  static const char* value(const ::limb_core_msgs::GetTactileState&) { return value(); }
};

template<>
struct DataType< ::limb_core_msgs::GetTactileState > {
  static const char* value()
  {
    return "limb_core_msgs/GetTactileState";
  }

  static const char* value(const ::limb_core_msgs::GetTactileState&) { return value(); }
};


// service_traits::MD5Sum< ::limb_core_msgs::GetTactileStateRequest> should match
// service_traits::MD5Sum< ::limb_core_msgs::GetTactileState >
template<>
struct MD5Sum< ::limb_core_msgs::GetTactileStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::limb_core_msgs::GetTactileState >::value();
  }
  static const char* value(const ::limb_core_msgs::GetTactileStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::limb_core_msgs::GetTactileStateRequest> should match
// service_traits::DataType< ::limb_core_msgs::GetTactileState >
template<>
struct DataType< ::limb_core_msgs::GetTactileStateRequest>
{
  static const char* value()
  {
    return DataType< ::limb_core_msgs::GetTactileState >::value();
  }
  static const char* value(const ::limb_core_msgs::GetTactileStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::limb_core_msgs::GetTactileStateResponse> should match
// service_traits::MD5Sum< ::limb_core_msgs::GetTactileState >
template<>
struct MD5Sum< ::limb_core_msgs::GetTactileStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::limb_core_msgs::GetTactileState >::value();
  }
  static const char* value(const ::limb_core_msgs::GetTactileStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::limb_core_msgs::GetTactileStateResponse> should match
// service_traits::DataType< ::limb_core_msgs::GetTactileState >
template<>
struct DataType< ::limb_core_msgs::GetTactileStateResponse>
{
  static const char* value()
  {
    return DataType< ::limb_core_msgs::GetTactileState >::value();
  }
  static const char* value(const ::limb_core_msgs::GetTactileStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIMB_CORE_MSGS_MESSAGE_GETTACTILESTATE_H
