// Generated by gencpp from file limb_core_msgs/MetaServiceRequest.msg
// DO NOT EDIT!


#ifndef LIMB_CORE_MSGS_MESSAGE_METASERVICEREQUEST_H
#define LIMB_CORE_MSGS_MESSAGE_METASERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace limb_core_msgs
{
template <class ContainerAllocator>
struct MetaServiceRequest_
{
  typedef MetaServiceRequest_<ContainerAllocator> Type;

  MetaServiceRequest_()
    : task_name()  {
    }
  MetaServiceRequest_(const ContainerAllocator& _alloc)
    : task_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _task_name_type;
  _task_name_type task_name;





  typedef boost::shared_ptr< ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MetaServiceRequest_

typedef ::limb_core_msgs::MetaServiceRequest_<std::allocator<void> > MetaServiceRequest;

typedef boost::shared_ptr< ::limb_core_msgs::MetaServiceRequest > MetaServiceRequestPtr;
typedef boost::shared_ptr< ::limb_core_msgs::MetaServiceRequest const> MetaServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator1> & lhs, const ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.task_name == rhs.task_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator1> & lhs, const ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace limb_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cfe37cdddcaaf5bd95f630c73751773b";
  }

  static const char* value(const ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcfe37cdddcaaf5bdULL;
  static const uint64_t static_value2 = 0x95f630c73751773bULL;
};

template<class ContainerAllocator>
struct DataType< ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "limb_core_msgs/MetaServiceRequest";
  }

  static const char* value(const ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string task_name\n"
;
  }

  static const char* value(const ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MetaServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::limb_core_msgs::MetaServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "task_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.task_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIMB_CORE_MSGS_MESSAGE_METASERVICEREQUEST_H
