// Generated by gencpp from file limb_core_msgs/MetaServiceResponse.msg
// DO NOT EDIT!


#ifndef LIMB_CORE_MSGS_MESSAGE_METASERVICERESPONSE_H
#define LIMB_CORE_MSGS_MESSAGE_METASERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace limb_core_msgs
{
template <class ContainerAllocator>
struct MetaServiceResponse_
{
  typedef MetaServiceResponse_<ContainerAllocator> Type;

  MetaServiceResponse_()
    : success(false)
    , message()  {
    }
  MetaServiceResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MetaServiceResponse_

typedef ::limb_core_msgs::MetaServiceResponse_<std::allocator<void> > MetaServiceResponse;

typedef boost::shared_ptr< ::limb_core_msgs::MetaServiceResponse > MetaServiceResponsePtr;
typedef boost::shared_ptr< ::limb_core_msgs::MetaServiceResponse const> MetaServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator1> & lhs, const ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator1> & lhs, const ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace limb_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "limb_core_msgs/MetaServiceResponse";
  }

  static const char* value(const ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MetaServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::limb_core_msgs::MetaServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIMB_CORE_MSGS_MESSAGE_METASERVICERESPONSE_H
