// Generated by gencpp from file limb_core_msgs/MetaService.msg
// DO NOT EDIT!


#ifndef LIMB_CORE_MSGS_MESSAGE_METASERVICE_H
#define LIMB_CORE_MSGS_MESSAGE_METASERVICE_H

#include <ros/service_traits.h>


#include <limb_core_msgs/MetaServiceRequest.h>
#include <limb_core_msgs/MetaServiceResponse.h>


namespace limb_core_msgs
{

struct MetaService
{

typedef MetaServiceRequest Request;
typedef MetaServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MetaService
} // namespace limb_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::limb_core_msgs::MetaService > {
  static const char* value()
  {
    return "4b165db9d12f9655e6774b3e72fa417f";
  }

  static const char* value(const ::limb_core_msgs::MetaService&) { return value(); }
};

template<>
struct DataType< ::limb_core_msgs::MetaService > {
  static const char* value()
  {
    return "limb_core_msgs/MetaService";
  }

  static const char* value(const ::limb_core_msgs::MetaService&) { return value(); }
};


// service_traits::MD5Sum< ::limb_core_msgs::MetaServiceRequest> should match
// service_traits::MD5Sum< ::limb_core_msgs::MetaService >
template<>
struct MD5Sum< ::limb_core_msgs::MetaServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::limb_core_msgs::MetaService >::value();
  }
  static const char* value(const ::limb_core_msgs::MetaServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::limb_core_msgs::MetaServiceRequest> should match
// service_traits::DataType< ::limb_core_msgs::MetaService >
template<>
struct DataType< ::limb_core_msgs::MetaServiceRequest>
{
  static const char* value()
  {
    return DataType< ::limb_core_msgs::MetaService >::value();
  }
  static const char* value(const ::limb_core_msgs::MetaServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::limb_core_msgs::MetaServiceResponse> should match
// service_traits::MD5Sum< ::limb_core_msgs::MetaService >
template<>
struct MD5Sum< ::limb_core_msgs::MetaServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::limb_core_msgs::MetaService >::value();
  }
  static const char* value(const ::limb_core_msgs::MetaServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::limb_core_msgs::MetaServiceResponse> should match
// service_traits::DataType< ::limb_core_msgs::MetaService >
template<>
struct DataType< ::limb_core_msgs::MetaServiceResponse>
{
  static const char* value()
  {
    return DataType< ::limb_core_msgs::MetaService >::value();
  }
  static const char* value(const ::limb_core_msgs::MetaServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIMB_CORE_MSGS_MESSAGE_METASERVICE_H
